### ISSUE TITLE
VR Implementation

### ISSUE THREAD

**Issue by Zorten** [Zelocity/XCITE-Chem-Equilibrium#6]

**Comment by MarioArceAcosta** [comment]
Zergio and I can get started on this. So far the VR implementation looks like it's going to include the ability
1) to grab molecules and 
2) combine them 
3) as a player within the box.

**Comment by Zelocity** [comment]
Duplicate AR Project so that it has the same functional code, then add in VR components, like Alexis' control panel. New Repository for VR will be created and link will be posted here.

**Comment by Zelocity** [comment]
https://github.com/Zelocity/XCITE-Chem-Equilibrium-VR
